exclude:
- LICENSE.txt
- vendor/
markdown: kramdown
permalink: /:categories/:title/
timezone: America/Chicago

# https://help.github.com/articles/using-jekyll-with-pages#configuration-overrides
lsi: false
safe: true
#source: .
